alg_name: "WISE"
model_name: "./my_exp/models/Qwen2.5-3B"
device: 0

mask_ratio: 0.2
edit_lr: 1.0
n_iter: 20
norm_constraint: 1.0
act_margin: [5.0, 20.0, 10.0]
act_ratio: 0.88
save_freq: 1
merge_freq: 5
merge_alg: "ties"
objective_optimization: "only_label"
inner_params:
  - "model.layers[24].mlp.down_proj.weight"

densities: 0.53
weights: 1.0

retrieve: true
replay: false

batch_size: 1
max_length: 32
model_parallel: false
use_chat_template: false
fp16: true

save_path: null
load_path: null
